/********************************************************************************
** Form generated from reading UI file 'dialog_measure_set.ui'
**
** Created by: Qt User Interface Compiler version 5.14.1
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_DIALOG_MEASURE_SET_H
#define UI_DIALOG_MEASURE_SET_H

#include <QtCore/QVariant>
#include <QtWidgets/QApplication>
#include <QtWidgets/QCheckBox>
#include <QtWidgets/QDialog>
#include <QtWidgets/QLabel>
#include <QtWidgets/QLineEdit>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QSlider>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_Dialog_measure_set
{
public:
    QLabel *label_2;
    QWidget *widget_2;
    QCheckBox *fft_4;
    QCheckBox *fft_2;
    QCheckBox *fft_1;
    QCheckBox *fft_3;
    QCheckBox *fft_6;
    QCheckBox *fft_5;
    QCheckBox *fft_7;
    QLabel *label_5;
    QLineEdit *lineEdit;
    QLabel *label_6;
    QLabel *label_7;
    QLabel *label_8;
    QWidget *widget_3;
    QCheckBox *hf_1;
    QCheckBox *hf_2;
    QCheckBox *hf_4;
    QCheckBox *hf_5;
    QCheckBox *hf_3;
    QWidget *widget_4;
    QCheckBox *lf_1;
    QCheckBox *lf_2;
    QCheckBox *lf_3;
    QCheckBox *lf_4;
    QCheckBox *lf_5;
    QCheckBox *lf_6;
    QCheckBox *lf_7;
    QCheckBox *lf_8;
    QCheckBox *lf_9;
    QCheckBox *lf_10;
    QWidget *widget_5;
    QCheckBox *tf_1;
    QCheckBox *tf_2;
    QWidget *widget_6;
    QLabel *label_3;
    QPushButton *set_ok;
    QPushButton *set_cancle;
    QLabel *label_11;
    QWidget *widget_7;
    QCheckBox *checkBox_15;
    QCheckBox *checkBox_16;
    QCheckBox *checkBox_17;
    QLabel *label_12;
    QWidget *widget_8;
    QCheckBox *s_1;
    QCheckBox *s_3;
    QCheckBox *s_5;
    QCheckBox *s_4;
    QCheckBox *s_2;
    QCheckBox *s_6;
    QCheckBox *s_7;
    QCheckBox *s_8;
    QLabel *label_13;
    QWidget *widget_9;
    QCheckBox *v_1;
    QCheckBox *v_2;
    QCheckBox *v_3;
    QCheckBox *v_4;
    QCheckBox *v_5;
    QLabel *label_14;
    QWidget *widget_10;
    QCheckBox *a_1;
    QCheckBox *a_5;
    QCheckBox *a_6;
    QCheckBox *a_8;
    QCheckBox *a_2;
    QCheckBox *a_4;
    QCheckBox *a_3;
    QCheckBox *a_7;
    QLabel *label_15;
    QLabel *label_16;
    QWidget *widget_11;
    QCheckBox *NET;
    QCheckBox *USB;
    QLabel *label_9;
    QWidget *widget_12;
    QCheckBox *if_S;
    QCheckBox *if_D;
    QCheckBox *if_A;
    QCheckBox *if_O;
    QLabel *label_10;
    QLabel *label_17;
    QSlider *horizontalSlider;
    QLineEdit *lineEdit_2;

    void setupUi(QDialog *Dialog_measure_set)
    {
        if (Dialog_measure_set->objectName().isEmpty())
            Dialog_measure_set->setObjectName(QString::fromUtf8("Dialog_measure_set"));
        Dialog_measure_set->resize(1226, 962);
        label_2 = new QLabel(Dialog_measure_set);
        label_2->setObjectName(QString::fromUtf8("label_2"));
        label_2->setGeometry(QRect(620, 0, 45, 31));
        widget_2 = new QWidget(Dialog_measure_set);
        widget_2->setObjectName(QString::fromUtf8("widget_2"));
        widget_2->setGeometry(QRect(650, 30, 121, 211));
        fft_4 = new QCheckBox(widget_2);
        fft_4->setObjectName(QString::fromUtf8("fft_4"));
        fft_4->setGeometry(QRect(0, 150, 87, 19));
        fft_4->setAutoExclusive(true);
        fft_2 = new QCheckBox(widget_2);
        fft_2->setObjectName(QString::fromUtf8("fft_2"));
        fft_2->setGeometry(QRect(0, 92, 87, 19));
        fft_2->setAutoExclusive(true);
        fft_1 = new QCheckBox(widget_2);
        fft_1->setObjectName(QString::fromUtf8("fft_1"));
        fft_1->setGeometry(QRect(0, 62, 87, 19));
        fft_1->setAutoExclusive(true);
        fft_3 = new QCheckBox(widget_2);
        fft_3->setObjectName(QString::fromUtf8("fft_3"));
        fft_3->setGeometry(QRect(0, 122, 87, 19));
        fft_3->setAutoExclusive(true);
        fft_6 = new QCheckBox(widget_2);
        fft_6->setObjectName(QString::fromUtf8("fft_6"));
        fft_6->setGeometry(QRect(0, 2, 87, 19));
        fft_6->setAutoExclusive(true);
        fft_5 = new QCheckBox(widget_2);
        fft_5->setObjectName(QString::fromUtf8("fft_5"));
        fft_5->setGeometry(QRect(0, 32, 87, 19));
        fft_5->setAutoExclusive(true);
        fft_7 = new QCheckBox(widget_2);
        fft_7->setObjectName(QString::fromUtf8("fft_7"));
        fft_7->setGeometry(QRect(0, 180, 87, 19));
        fft_7->setAutoExclusive(true);
        label_5 = new QLabel(Dialog_measure_set);
        label_5->setObjectName(QString::fromUtf8("label_5"));
        label_5->setGeometry(QRect(840, 10, 81, 41));
        lineEdit = new QLineEdit(Dialog_measure_set);
        lineEdit->setObjectName(QString::fromUtf8("lineEdit"));
        lineEdit->setGeometry(QRect(840, 50, 81, 41));
        label_6 = new QLabel(Dialog_measure_set);
        label_6->setObjectName(QString::fromUtf8("label_6"));
        label_6->setGeometry(QRect(30, 260, 81, 31));
        label_7 = new QLabel(Dialog_measure_set);
        label_7->setObjectName(QString::fromUtf8("label_7"));
        label_7->setGeometry(QRect(230, 260, 81, 31));
        label_8 = new QLabel(Dialog_measure_set);
        label_8->setObjectName(QString::fromUtf8("label_8"));
        label_8->setGeometry(QRect(430, 260, 81, 31));
        widget_3 = new QWidget(Dialog_measure_set);
        widget_3->setObjectName(QString::fromUtf8("widget_3"));
        widget_3->setGeometry(QRect(70, 290, 121, 221));
        hf_1 = new QCheckBox(widget_3);
        hf_1->setObjectName(QString::fromUtf8("hf_1"));
        hf_1->setGeometry(QRect(0, 10, 87, 19));
        hf_1->setAutoExclusive(true);
        hf_2 = new QCheckBox(widget_3);
        hf_2->setObjectName(QString::fromUtf8("hf_2"));
        hf_2->setGeometry(QRect(0, 40, 87, 19));
        hf_2->setAutoExclusive(true);
        hf_4 = new QCheckBox(widget_3);
        hf_4->setObjectName(QString::fromUtf8("hf_4"));
        hf_4->setGeometry(QRect(0, 100, 87, 19));
        hf_4->setAutoExclusive(true);
        hf_5 = new QCheckBox(widget_3);
        hf_5->setObjectName(QString::fromUtf8("hf_5"));
        hf_5->setGeometry(QRect(0, 130, 87, 19));
        hf_5->setAutoExclusive(true);
        hf_3 = new QCheckBox(widget_3);
        hf_3->setObjectName(QString::fromUtf8("hf_3"));
        hf_3->setGeometry(QRect(0, 70, 87, 19));
        hf_3->setAutoExclusive(true);
        widget_4 = new QWidget(Dialog_measure_set);
        widget_4->setObjectName(QString::fromUtf8("widget_4"));
        widget_4->setGeometry(QRect(280, 290, 121, 321));
        lf_1 = new QCheckBox(widget_4);
        lf_1->setObjectName(QString::fromUtf8("lf_1"));
        lf_1->setGeometry(QRect(0, 10, 87, 19));
        lf_1->setAutoExclusive(true);
        lf_2 = new QCheckBox(widget_4);
        lf_2->setObjectName(QString::fromUtf8("lf_2"));
        lf_2->setGeometry(QRect(0, 40, 87, 19));
        lf_2->setAutoExclusive(true);
        lf_3 = new QCheckBox(widget_4);
        lf_3->setObjectName(QString::fromUtf8("lf_3"));
        lf_3->setGeometry(QRect(0, 70, 87, 19));
        lf_3->setAutoExclusive(true);
        lf_4 = new QCheckBox(widget_4);
        lf_4->setObjectName(QString::fromUtf8("lf_4"));
        lf_4->setGeometry(QRect(0, 100, 87, 19));
        lf_4->setAutoExclusive(true);
        lf_5 = new QCheckBox(widget_4);
        lf_5->setObjectName(QString::fromUtf8("lf_5"));
        lf_5->setGeometry(QRect(0, 130, 87, 19));
        lf_5->setAutoExclusive(true);
        lf_6 = new QCheckBox(widget_4);
        lf_6->setObjectName(QString::fromUtf8("lf_6"));
        lf_6->setGeometry(QRect(0, 160, 87, 19));
        lf_6->setAutoExclusive(true);
        lf_7 = new QCheckBox(widget_4);
        lf_7->setObjectName(QString::fromUtf8("lf_7"));
        lf_7->setGeometry(QRect(0, 190, 87, 19));
        lf_7->setAutoExclusive(true);
        lf_8 = new QCheckBox(widget_4);
        lf_8->setObjectName(QString::fromUtf8("lf_8"));
        lf_8->setGeometry(QRect(0, 220, 87, 19));
        lf_8->setAutoExclusive(true);
        lf_9 = new QCheckBox(widget_4);
        lf_9->setObjectName(QString::fromUtf8("lf_9"));
        lf_9->setGeometry(QRect(0, 250, 87, 19));
        lf_9->setAutoExclusive(true);
        lf_10 = new QCheckBox(widget_4);
        lf_10->setObjectName(QString::fromUtf8("lf_10"));
        lf_10->setGeometry(QRect(0, 280, 87, 19));
        lf_10->setAutoExclusive(true);
        widget_5 = new QWidget(Dialog_measure_set);
        widget_5->setObjectName(QString::fromUtf8("widget_5"));
        widget_5->setGeometry(QRect(500, 290, 120, 131));
        tf_1 = new QCheckBox(widget_5);
        tf_1->setObjectName(QString::fromUtf8("tf_1"));
        tf_1->setGeometry(QRect(0, 10, 87, 19));
        tf_1->setAutoExclusive(true);
        tf_2 = new QCheckBox(widget_5);
        tf_2->setObjectName(QString::fromUtf8("tf_2"));
        tf_2->setGeometry(QRect(0, 50, 87, 19));
        tf_2->setAutoExclusive(true);
        widget_6 = new QWidget(Dialog_measure_set);
        widget_6->setObjectName(QString::fromUtf8("widget_6"));
        widget_6->setGeometry(QRect(60, 820, 361, 111));
        label_3 = new QLabel(widget_6);
        label_3->setObjectName(QString::fromUtf8("label_3"));
        label_3->setGeometry(QRect(20, 20, 131, 20));
        set_ok = new QPushButton(widget_6);
        set_ok->setObjectName(QString::fromUtf8("set_ok"));
        set_ok->setGeometry(QRect(200, 80, 131, 28));
        set_cancle = new QPushButton(widget_6);
        set_cancle->setObjectName(QString::fromUtf8("set_cancle"));
        set_cancle->setGeometry(QRect(30, 80, 131, 28));
        label_11 = new QLabel(Dialog_measure_set);
        label_11->setObjectName(QString::fromUtf8("label_11"));
        label_11->setGeometry(QRect(410, 10, 61, 31));
        widget_7 = new QWidget(Dialog_measure_set);
        widget_7->setObjectName(QString::fromUtf8("widget_7"));
        widget_7->setGeometry(QRect(430, 40, 121, 131));
        checkBox_15 = new QCheckBox(widget_7);
        checkBox_15->setObjectName(QString::fromUtf8("checkBox_15"));
        checkBox_15->setGeometry(QRect(10, 10, 87, 19));
        checkBox_15->setAutoExclusive(true);
        checkBox_16 = new QCheckBox(widget_7);
        checkBox_16->setObjectName(QString::fromUtf8("checkBox_16"));
        checkBox_16->setGeometry(QRect(10, 50, 87, 16));
        checkBox_16->setAutoExclusive(true);
        checkBox_17 = new QCheckBox(widget_7);
        checkBox_17->setObjectName(QString::fromUtf8("checkBox_17"));
        checkBox_17->setGeometry(QRect(10, 90, 87, 19));
        checkBox_17->setAutoFillBackground(false);
        checkBox_17->setAutoExclusive(true);
        label_12 = new QLabel(Dialog_measure_set);
        label_12->setObjectName(QString::fromUtf8("label_12"));
        label_12->setGeometry(QRect(650, 260, 61, 31));
        widget_8 = new QWidget(Dialog_measure_set);
        widget_8->setObjectName(QString::fromUtf8("widget_8"));
        widget_8->setGeometry(QRect(670, 290, 120, 281));
        s_1 = new QCheckBox(widget_8);
        s_1->setObjectName(QString::fromUtf8("s_1"));
        s_1->setGeometry(QRect(0, 10, 101, 20));
        s_1->setAutoExclusive(true);
        s_3 = new QCheckBox(widget_8);
        s_3->setObjectName(QString::fromUtf8("s_3"));
        s_3->setGeometry(QRect(0, 70, 101, 20));
        s_3->setAutoExclusive(true);
        s_5 = new QCheckBox(widget_8);
        s_5->setObjectName(QString::fromUtf8("s_5"));
        s_5->setGeometry(QRect(0, 130, 101, 20));
        s_5->setAutoExclusive(true);
        s_4 = new QCheckBox(widget_8);
        s_4->setObjectName(QString::fromUtf8("s_4"));
        s_4->setGeometry(QRect(0, 100, 101, 20));
        s_4->setAutoExclusive(true);
        s_2 = new QCheckBox(widget_8);
        s_2->setObjectName(QString::fromUtf8("s_2"));
        s_2->setGeometry(QRect(0, 40, 101, 20));
        s_2->setAutoExclusive(true);
        s_6 = new QCheckBox(widget_8);
        s_6->setObjectName(QString::fromUtf8("s_6"));
        s_6->setGeometry(QRect(0, 160, 101, 20));
        s_6->setAutoExclusive(true);
        s_7 = new QCheckBox(widget_8);
        s_7->setObjectName(QString::fromUtf8("s_7"));
        s_7->setGeometry(QRect(0, 190, 101, 20));
        s_7->setAutoExclusive(true);
        s_8 = new QCheckBox(widget_8);
        s_8->setObjectName(QString::fromUtf8("s_8"));
        s_8->setGeometry(QRect(0, 220, 101, 16));
        s_8->setAutoExclusive(true);
        label_13 = new QLabel(Dialog_measure_set);
        label_13->setObjectName(QString::fromUtf8("label_13"));
        label_13->setGeometry(QRect(820, 260, 61, 31));
        widget_9 = new QWidget(Dialog_measure_set);
        widget_9->setObjectName(QString::fromUtf8("widget_9"));
        widget_9->setGeometry(QRect(870, 290, 120, 261));
        v_1 = new QCheckBox(widget_9);
        v_1->setObjectName(QString::fromUtf8("v_1"));
        v_1->setGeometry(QRect(0, 10, 101, 20));
        v_1->setAutoExclusive(true);
        v_2 = new QCheckBox(widget_9);
        v_2->setObjectName(QString::fromUtf8("v_2"));
        v_2->setGeometry(QRect(0, 40, 101, 20));
        v_2->setAutoExclusive(true);
        v_3 = new QCheckBox(widget_9);
        v_3->setObjectName(QString::fromUtf8("v_3"));
        v_3->setGeometry(QRect(0, 70, 101, 20));
        v_3->setAutoExclusive(true);
        v_4 = new QCheckBox(widget_9);
        v_4->setObjectName(QString::fromUtf8("v_4"));
        v_4->setGeometry(QRect(0, 100, 101, 20));
        v_4->setAutoExclusive(true);
        v_5 = new QCheckBox(widget_9);
        v_5->setObjectName(QString::fromUtf8("v_5"));
        v_5->setGeometry(QRect(0, 130, 101, 20));
        v_5->setAutoExclusive(true);
        label_14 = new QLabel(Dialog_measure_set);
        label_14->setObjectName(QString::fromUtf8("label_14"));
        label_14->setGeometry(QRect(1000, 260, 81, 31));
        widget_10 = new QWidget(Dialog_measure_set);
        widget_10->setObjectName(QString::fromUtf8("widget_10"));
        widget_10->setGeometry(QRect(1050, 280, 120, 261));
        a_1 = new QCheckBox(widget_10);
        a_1->setObjectName(QString::fromUtf8("a_1"));
        a_1->setGeometry(QRect(0, 10, 101, 20));
        a_1->setAutoExclusive(true);
        a_5 = new QCheckBox(widget_10);
        a_5->setObjectName(QString::fromUtf8("a_5"));
        a_5->setGeometry(QRect(0, 130, 101, 20));
        a_5->setAutoExclusive(true);
        a_6 = new QCheckBox(widget_10);
        a_6->setObjectName(QString::fromUtf8("a_6"));
        a_6->setGeometry(QRect(0, 160, 101, 20));
        a_6->setAutoExclusive(true);
        a_8 = new QCheckBox(widget_10);
        a_8->setObjectName(QString::fromUtf8("a_8"));
        a_8->setGeometry(QRect(0, 220, 101, 20));
        a_8->setAutoExclusive(true);
        a_2 = new QCheckBox(widget_10);
        a_2->setObjectName(QString::fromUtf8("a_2"));
        a_2->setGeometry(QRect(0, 40, 101, 20));
        a_2->setAutoExclusive(true);
        a_4 = new QCheckBox(widget_10);
        a_4->setObjectName(QString::fromUtf8("a_4"));
        a_4->setGeometry(QRect(0, 100, 101, 20));
        a_4->setAutoExclusive(true);
        a_3 = new QCheckBox(widget_10);
        a_3->setObjectName(QString::fromUtf8("a_3"));
        a_3->setGeometry(QRect(0, 70, 101, 20));
        a_3->setAutoExclusive(true);
        a_7 = new QCheckBox(widget_10);
        a_7->setObjectName(QString::fromUtf8("a_7"));
        a_7->setGeometry(QRect(0, 190, 101, 20));
        a_7->setAutoExclusive(true);
        label_15 = new QLabel(Dialog_measure_set);
        label_15->setObjectName(QString::fromUtf8("label_15"));
        label_15->setGeometry(QRect(890, 260, 31, 31));
        label_16 = new QLabel(Dialog_measure_set);
        label_16->setObjectName(QString::fromUtf8("label_16"));
        label_16->setGeometry(QRect(1080, 260, 31, 31));
        widget_11 = new QWidget(Dialog_measure_set);
        widget_11->setObjectName(QString::fromUtf8("widget_11"));
        widget_11->setGeometry(QRect(40, 40, 91, 81));
        NET = new QCheckBox(widget_11);
        NET->setObjectName(QString::fromUtf8("NET"));
        NET->setGeometry(QRect(0, 10, 87, 19));
        NET->setAutoExclusive(true);
        USB = new QCheckBox(widget_11);
        USB->setObjectName(QString::fromUtf8("USB"));
        USB->setGeometry(QRect(0, 50, 87, 19));
        USB->setAutoExclusive(true);
        label_9 = new QLabel(Dialog_measure_set);
        label_9->setObjectName(QString::fromUtf8("label_9"));
        label_9->setGeometry(QRect(30, 10, 31, 31));
        widget_12 = new QWidget(Dialog_measure_set);
        widget_12->setObjectName(QString::fromUtf8("widget_12"));
        widget_12->setGeometry(QRect(240, 40, 81, 181));
        if_S = new QCheckBox(widget_12);
        if_S->setObjectName(QString::fromUtf8("if_S"));
        if_S->setGeometry(QRect(0, 10, 87, 19));
        if_S->setAutoExclusive(true);
        if_D = new QCheckBox(widget_12);
        if_D->setObjectName(QString::fromUtf8("if_D"));
        if_D->setGeometry(QRect(0, 50, 87, 16));
        if_D->setAutoExclusive(true);
        if_A = new QCheckBox(widget_12);
        if_A->setObjectName(QString::fromUtf8("if_A"));
        if_A->setGeometry(QRect(0, 90, 87, 16));
        if_A->setAutoExclusive(true);
        if_O = new QCheckBox(widget_12);
        if_O->setObjectName(QString::fromUtf8("if_O"));
        if_O->setGeometry(QRect(0, 130, 87, 16));
        if_O->setAutoExclusive(true);
        label_10 = new QLabel(Dialog_measure_set);
        label_10->setObjectName(QString::fromUtf8("label_10"));
        label_10->setGeometry(QRect(190, 10, 71, 31));
        label_17 = new QLabel(Dialog_measure_set);
        label_17->setObjectName(QString::fromUtf8("label_17"));
        label_17->setGeometry(QRect(20, 600, 81, 31));
        horizontalSlider = new QSlider(Dialog_measure_set);
        horizontalSlider->setObjectName(QString::fromUtf8("horizontalSlider"));
        horizontalSlider->setGeometry(QRect(50, 650, 160, 22));
        horizontalSlider->setMaximum(7);
        horizontalSlider->setOrientation(Qt::Horizontal);
        lineEdit_2 = new QLineEdit(Dialog_measure_set);
        lineEdit_2->setObjectName(QString::fromUtf8("lineEdit_2"));
        lineEdit_2->setGeometry(QRect(240, 650, 113, 20));

        retranslateUi(Dialog_measure_set);

        QMetaObject::connectSlotsByName(Dialog_measure_set);
    } // setupUi

    void retranslateUi(QDialog *Dialog_measure_set)
    {
        Dialog_measure_set->setWindowTitle(QCoreApplication::translate("Dialog_measure_set", "\350\256\276\347\275\256", nullptr));
        label_2->setText(QCoreApplication::translate("Dialog_measure_set", "\350\260\261\347\272\277\346\225\260", nullptr));
        fft_4->setText(QCoreApplication::translate("Dialog_measure_set", "3125", nullptr));
        fft_2->setText(QCoreApplication::translate("Dialog_measure_set", "12500", nullptr));
        fft_1->setText(QCoreApplication::translate("Dialog_measure_set", "25000", nullptr));
        fft_3->setText(QCoreApplication::translate("Dialog_measure_set", "6250", nullptr));
        fft_6->setText(QCoreApplication::translate("Dialog_measure_set", "250000", nullptr));
        fft_5->setText(QCoreApplication::translate("Dialog_measure_set", "50000", nullptr));
        fft_7->setText(QCoreApplication::translate("Dialog_measure_set", "250", nullptr));
        label_5->setText(QCoreApplication::translate("Dialog_measure_set", "\346\265\213\351\207\217\346\227\266\351\225\277/s", nullptr));
        label_6->setText(QCoreApplication::translate("Dialog_measure_set", "\351\253\230\351\200\232\346\273\244\346\263\242\345\231\250", nullptr));
        label_7->setText(QCoreApplication::translate("Dialog_measure_set", "\344\275\216\351\200\232\346\273\244\346\263\242\345\231\250", nullptr));
        label_8->setText(QCoreApplication::translate("Dialog_measure_set", "\350\267\237\350\270\252\346\273\244\346\263\242\345\231\250", nullptr));
        hf_1->setText(QCoreApplication::translate("Dialog_measure_set", "\346\227\240", nullptr));
        hf_2->setText(QCoreApplication::translate("Dialog_measure_set", "5Hz", nullptr));
        hf_4->setText(QCoreApplication::translate("Dialog_measure_set", "20Hz", nullptr));
        hf_5->setText(QCoreApplication::translate("Dialog_measure_set", "80Hz", nullptr));
        hf_3->setText(QCoreApplication::translate("Dialog_measure_set", "10Hz", nullptr));
        lf_1->setText(QCoreApplication::translate("Dialog_measure_set", "\346\227\240", nullptr));
        lf_2->setText(QCoreApplication::translate("Dialog_measure_set", "2kHz", nullptr));
        lf_3->setText(QCoreApplication::translate("Dialog_measure_set", "10kHz", nullptr));
        lf_4->setText(QCoreApplication::translate("Dialog_measure_set", "15kHz", nullptr));
        lf_5->setText(QCoreApplication::translate("Dialog_measure_set", "200kHz", nullptr));
        lf_6->setText(QCoreApplication::translate("Dialog_measure_set", "1MHz", nullptr));
        lf_7->setText(QCoreApplication::translate("Dialog_measure_set", "1.5MHz", nullptr));
        lf_8->setText(QCoreApplication::translate("Dialog_measure_set", "1.6MHz", nullptr));
        lf_9->setText(QCoreApplication::translate("Dialog_measure_set", "8MHz", nullptr));
        lf_10->setText(QCoreApplication::translate("Dialog_measure_set", "12MHz", nullptr));
        tf_1->setText(QCoreApplication::translate("Dialog_measure_set", "\346\227\240", nullptr));
        tf_2->setText(QCoreApplication::translate("Dialog_measure_set", "\346\234\211", nullptr));
        label_3->setText(QCoreApplication::translate("Dialog_measure_set", "\344\270\212\350\277\260\344\277\256\346\224\271\345\206\231\345\205\245\351\205\215\347\275\256", nullptr));
        set_ok->setText(QCoreApplication::translate("Dialog_measure_set", "\347\241\256\345\256\232", nullptr));
        set_cancle->setText(QCoreApplication::translate("Dialog_measure_set", "\345\217\226\346\266\210", nullptr));
        label_11->setText(QCoreApplication::translate("Dialog_measure_set", "\351\242\221\347\216\207\351\207\217\347\250\213", nullptr));
        checkBox_15->setText(QCoreApplication::translate("Dialog_measure_set", "0-25kHz", nullptr));
        checkBox_16->setText(QCoreApplication::translate("Dialog_measure_set", "0-2.5MHz", nullptr));
        checkBox_17->setText(QCoreApplication::translate("Dialog_measure_set", "0-25MHz", nullptr));
        label_12->setText(QCoreApplication::translate("Dialog_measure_set", "\344\275\215\347\247\273\351\207\217\347\250\213", nullptr));
        s_1->setText(QCoreApplication::translate("Dialog_measure_set", "0-5nm", nullptr));
        s_3->setText(QCoreApplication::translate("Dialog_measure_set", "0-500nm", nullptr));
        s_5->setText(QCoreApplication::translate("Dialog_measure_set", "0-50um", nullptr));
        s_4->setText(QCoreApplication::translate("Dialog_measure_set", "0-5um", nullptr));
        s_2->setText(QCoreApplication::translate("Dialog_measure_set", "0-50nm", nullptr));
        s_6->setText(QCoreApplication::translate("Dialog_measure_set", "0-500um", nullptr));
        s_7->setText(QCoreApplication::translate("Dialog_measure_set", "0-5mm", nullptr));
        s_8->setText(QCoreApplication::translate("Dialog_measure_set", "0-50mm", nullptr));
        label_13->setText(QCoreApplication::translate("Dialog_measure_set", "\351\200\237\345\272\246\351\207\217\347\250\213", nullptr));
        v_1->setText(QCoreApplication::translate("Dialog_measure_set", "0-0.001", nullptr));
        v_2->setText(QCoreApplication::translate("Dialog_measure_set", "0-0.01", nullptr));
        v_3->setText(QCoreApplication::translate("Dialog_measure_set", "0-0.1", nullptr));
        v_4->setText(QCoreApplication::translate("Dialog_measure_set", "0-1", nullptr));
        v_5->setText(QCoreApplication::translate("Dialog_measure_set", "0-10", nullptr));
        label_14->setText(QCoreApplication::translate("Dialog_measure_set", "\345\212\240\351\200\237\345\272\246\351\207\217\347\250\213", nullptr));
        a_1->setText(QCoreApplication::translate("Dialog_measure_set", "16", nullptr));
        a_5->setText(QCoreApplication::translate("Dialog_measure_set", "1.6e5", nullptr));
        a_6->setText(QCoreApplication::translate("Dialog_measure_set", "1.6e6", nullptr));
        a_8->setText(QCoreApplication::translate("Dialog_measure_set", "1.6e7", nullptr));
        a_2->setText(QCoreApplication::translate("Dialog_measure_set", "160", nullptr));
        a_4->setText(QCoreApplication::translate("Dialog_measure_set", "1.6e4", nullptr));
        a_3->setText(QCoreApplication::translate("Dialog_measure_set", "1.6e3", nullptr));
        a_7->setText(QCoreApplication::translate("Dialog_measure_set", "1.0e7", nullptr));
        label_15->setText(QCoreApplication::translate("Dialog_measure_set", "m/s", nullptr));
        label_16->setText(QCoreApplication::translate("Dialog_measure_set", "/g", nullptr));
        NET->setText(QCoreApplication::translate("Dialog_measure_set", "\347\275\221\345\217\243", nullptr));
        USB->setText(QCoreApplication::translate("Dialog_measure_set", "USB", nullptr));
        label_9->setText(QCoreApplication::translate("Dialog_measure_set", "\351\200\232\350\256\257", nullptr));
        if_S->setText(QCoreApplication::translate("Dialog_measure_set", "\344\275\215\347\247\273", nullptr));
        if_D->setText(QCoreApplication::translate("Dialog_measure_set", "\351\200\237\345\272\246", nullptr));
        if_A->setText(QCoreApplication::translate("Dialog_measure_set", "\345\212\240\351\200\237\345\272\246", nullptr));
        if_O->setText(QCoreApplication::translate("Dialog_measure_set", "\345\216\237\345\247\213\346\225\260\346\215\256", nullptr));
        label_10->setText(QCoreApplication::translate("Dialog_measure_set", "\346\265\213\351\207\217", nullptr));
        label_17->setText(QCoreApplication::translate("Dialog_measure_set", "BNC\346\250\241\346\213\237\350\276\223\345\207\272", nullptr));
    } // retranslateUi

};

namespace Ui {
    class Dialog_measure_set: public Ui_Dialog_measure_set {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_DIALOG_MEASURE_SET_H
